package entities;
// Generated Feb 6, 2019 7:59:09 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Emisor generated by hbm2java
 */
@Entity
@Table(name = "emisores",
         catalog = "pruebas"
)
public class Emisor implements java.io.Serializable {

    private Integer idEmisor;
    private String nombre;
    private String direccion;
    private String rfc;

    public Emisor() {
    }

    public Emisor(String nombre, String direccion, String rfc) {
        this.nombre = nombre;
        this.direccion = direccion;
        this.rfc = rfc;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "IdEmisor", unique = true, nullable = false)
    public Integer getIdEmisor() {
        return this.idEmisor;
    }

    public void setIdEmisor(Integer idEmisor) {
        this.idEmisor = idEmisor;
    }

    @Column(name = "Nombre", nullable = false, length = 50)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Column(name = "Direccion", nullable = false, length = 50)
    public String getDireccion() {
        return this.direccion;
    }

    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    @Column(name = "RFC", nullable = false, length = 13)
    public String getRfc() {
        return this.rfc;
    }

    public void setRfc(String rfc) {
        this.rfc = rfc;
    }
}
